# Generated by Django 5.2.1 on 2025-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_faculty_designation_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
