# Generated by Django 5.2.1 on 2025-05-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_faculty_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='average_rating',
        ),
    ]
