# Generated by Django 5.2.1 on 2025-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_faculty_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Senior Lecturer', 'Senior Lecturer'), ('Lecturer', 'Lecturer')], max_length=50),
        ),
    ]
