# Generated by Django 5.2.1 on 2025-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='old_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
